In [1]:
!pip install yfinance

Requirement already satisfied: yfinance in c:\users\admin\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: pandas>=1.3.0 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\admin\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in c:\users\admin\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\admin\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2026.1.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\admin\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: pycparser in c:\users\admin\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)

In [3]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [75]:
# Download 5 years of daily data

reliance_ts = yf.download(
    "RELIANCE.NS",
    start="2020-01-01",
    end="2026-09-09",
    progress=False
)

canara_ts = yf.download(
    "CANBK.NS",
    start="2020-01-01",
    end="2026-09-09",
    progress=False
)

nifty_ts = yf.download(
    "^NSEI",
    start="2020-01-01",
    end="2026-09-09",
    progress=False
)

In [76]:
nifty_ts.head()

Price              Close          High           Low          Open  Volume
Ticker             ^NSEI         ^NSEI         ^NSEI         ^NSEI   ^NSEI
Date
2020-01-01  12182.500000  12222.200195  12165.299805  12202.150391  304100
2020-01-02  12282.200195  12289.900391  12195.250000  12198.549805  407700
2020-01-03  12226.650391  12265.599609  12191.349609  12261.099609  428800
2020-01-06  11993.049805  12179.099609  11974.200195  12170.599609  396500
2020-01-07  12052.950195  12152.150391  12005.349609  12079.099609  447800

In [29]:
print(nifty_ts.columns)

MultiIndex([( 'Close', '^NSEI'),
            (  'High', '^NSEI'),
            (   'Low', '^NSEI'),
            (  'Open', '^NSEI'),
            ('Volume', '^NSEI')],
           names=['Price', 'Ticker'])

In [77]:
reliance_ts = reliance_ts[['Close']]
canara_ts = canara_ts[['Close']]
nifty_ts = nifty_ts[['Close']]

In [78]:
reliance_ts.columns = ['Reliance']
canara_ts.columns = ['Canara']
nifty_ts.columns = ['Nifty']

In [79]:
nifty_ts.head()

                   Nifty
Date
2020-01-01  12182.500000
2020-01-02  12282.200195
2020-01-03  12226.650391
2020-01-06  11993.049805
2020-01-07  12052.950195

In [80]:
merged_df = pd.concat(
    [reliance_ts, canara_ts, nifty_ts],
    axis=1
)

merged_df.head()

              Reliance     Canara         Nifty
Date
2020-01-01  672.216125  37.519474  12182.500000
2020-01-02  683.660278  38.738239  12282.200195
2020-01-03  684.484009  37.519474  12226.650391
2020-01-06  668.609314  35.115788  11993.049805
2020-01-07  678.895691  35.217350  12052.950195

In [34]:
print(merged_df.columns)

Index(['Reliance', 'Canara', 'Nifty'], dtype='object')

In [35]:
import numpy as np

log_returns = np.log(
    merged_df[['Reliance', 'Canara', 'Nifty']] /
    merged_df[['Reliance', 'Canara', 'Nifty']].shift(1)
).dropna()

log_returns.head()

            Reliance    Canara     Nifty
Date
2020-01-02  0.016881  0.031967  0.008151
2020-01-03  0.001204 -0.031967 -0.004533
2020-01-06 -0.023465 -0.066209 -0.019291
2020-01-07  0.015268  0.002888  0.004982
2020-01-08 -0.007539 -0.001202 -0.002293

In [36]:
import statsmodels.api as sm

In [37]:
X = sm.add_constant(log_returns["Nifty"])
y = log_returns["Reliance"]

In [38]:
model_reliance = sm.OLS(y, X).fit()

In [40]:
print(model_reliance.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               Reliance   R-squared:                       0.497
Model:                            OLS   Adj. R-squared:                  0.497
Method:                 Least Squares   F-statistic:                     1628.
Date:                Thu, 10 Sep 2026   Prob (F-statistic):          4.25e-248
Time:                        16:40:00   Log-Likelihood:                 4901.8
No. Observations:                1649   AIC:                            -9800.
Df Residuals:                    1647   BIC:                            -9789.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.194e-05      0.000     -0.105      0.917      -0.001       0.001
Nifty          1.0887      0.027     40.347      0.000       1.036       1.142
==============================================================================
Omnibus:                      233.408   Durbin-Watson:                   1.915
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3084.154
Skew:                           0.037   Prob(JB):                         0.00
Kurtosis:                       9.699   Cond. No.                         88.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [41]:
X_c = sm.add_constant(log_returns["Nifty"])
y_c = log_returns["Canara"]

In [42]:
model_canara = sm.OLS(y_c, X_c).fit()

In [43]:
print(model_canara.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Canara   R-squared:                       0.393
Model:                            OLS   Adj. R-squared:                  0.392
Method:                 Least Squares   F-statistic:                     1065.
Date:                Thu, 10 Sep 2026   Prob (F-statistic):          1.26e-180
Time:                        16:41:18   Log-Likelihood:                 4136.8
No. Observations:                1649   AIC:                            -8270.
Df Residuals:                    1647   BIC:                            -8259.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0002      0.000      0.360      0.719      -0.001       0.001
Nifty          1.4005      0.043     32.638      0.000       1.316       1.485
==============================================================================
Omnibus:                      220.620   Durbin-Watson:                   2.054
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1397.659
Skew:                           0.442   Prob(JB):                    3.18e-304
Kurtosis:                       7.423   Cond. No.                         88.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [44]:
canara = yf.download(
    "CANBK.NS",
    start="2020-01-01",
    end="2026-09-01",
    interval="1mo",
    auto_adjust=False
)

nifty = yf.download(
    "^NSEI",
    start="2020-01-01",
    end="2026-09-01",
    interval="1mo",
    auto_adjust=False
)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [45]:
nifty.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI
Date,,,,,,
2020-01-01,11962.099609,11962.099609,12430.500000,11929.599609,12202.150391,10965400
2020-02-01,11201.750000,11201.750000,12246.700195,11175.049805,11627.450195,10198200
2020-03-01,8597.750000,8597.750000,11433.000000,7511.100098,11387.349609,21303000
2020-04-01,9859.900391,9859.900391,9889.049805,8055.799805,8584.099609,12736300
2020-05-01,9580.299805,9580.299805,9598.849609,8806.750000,9533.500000,13675900

In [46]:
canara = canara[['Close']]
nifty = nifty[['Close']]

In [51]:
canara.columns=['canara']
nifty.columns=['nifty']
nifty.head()

                   nifty
Date
2020-01-01  11962.099609
2020-02-01  11201.750000
2020-03-01   8597.750000
2020-04-01   9859.900391
2020-05-01   9580.299805

In [52]:
monthly_df = pd.concat(
    [ canara, nifty],
    axis=1
)

monthly_df.head()

               canara         nifty
Date
2020-01-01  40.529999  11962.099609
2020-02-01  28.740000  11201.750000
2020-03-01  18.100000   8597.750000
2020-04-01  17.580000   9859.900391
2020-05-01  16.760000   9580.299805

In [53]:
monthly_df['Rf'] = 0.5

In [54]:
monthly_df.head()

               canara         nifty   Rf
Date
2020-01-01  40.529999  11962.099609  0.5
2020-02-01  28.740000  11201.750000  0.5
2020-03-01  18.100000   8597.750000  0.5
2020-04-01  17.580000   9859.900391  0.5
2020-05-01  16.760000   9580.299805  0.5

In [56]:
monthly_df = np.log(
    monthly_df[['canara', 'nifty']] /
    monthly_df[[ 'canara', 'nifty']].shift(1)
).dropna()

monthly_df.head()

              canara     nifty
Date
2020-02-01 -0.343753 -0.065673
2020-03-01 -0.462378 -0.264569
2020-04-01 -0.029150  0.136976
2020-05-01 -0.047767 -0.028767
2020-06-01  0.182222  0.072639

In [57]:
monthly_df['Rf'] = 0.5

In [58]:
monthly_df.head()

              canara     nifty   Rf
Date
2020-02-01 -0.343753 -0.065673  0.5
2020-03-01 -0.462378 -0.264569  0.5
2020-04-01 -0.029150  0.136976  0.5
2020-05-01 -0.047767 -0.028767  0.5
2020-06-01  0.182222  0.072639  0.5

In [60]:
monthly_df['Canara_Excess'] = monthly_df['canara'] - monthly_df['Rf']
monthly_df['Nifty_Excess'] = monthly_df['nifty'] - monthly_df['Rf']

In [61]:
monthly_df.head()

              canara     nifty   Rf  Canara_Excess  Nifty_Excess
Date
2020-02-01 -0.343753 -0.065673  0.5      -0.843753     -0.565673
2020-03-01 -0.462378 -0.264569  0.5      -0.962378     -0.764569
2020-04-01 -0.029150  0.136976  0.5      -0.529150     -0.363024
2020-05-01 -0.047767 -0.028767  0.5      -0.547767     -0.528767
2020-06-01  0.182222  0.072639  0.5      -0.317778     -0.427361

In [66]:
X_m = sm.add_constant(monthly_df["nifty"])
y_m = monthly_df["canara"]

In [67]:
monthly_canara = sm.OLS(y_m, X_m).fit()

In [68]:
print(monthly_canara.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 canara   R-squared:                       0.516
Model:                            OLS   Adj. R-squared:                  0.509
Method:                 Least Squares   F-statistic:                     81.95
Date:                Thu, 10 Sep 2026   Prob (F-statistic):           9.48e-14
Time:                        21:19:04   Log-Likelihood:                 83.150
No. Observations:                  79   AIC:                            -162.3
Df Residuals:                      77   BIC:                            -157.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0002      0.010     -0.017      0.986      -0.020       0.019
nifty          1.6505      0.182      9.053      0.000       1.287       2.014
==============================================================================
Omnibus:                        3.941   Durbin-Watson:                   1.796
Prob(Omnibus):                  0.139   Jarque-Bera (JB):                4.582
Skew:                           0.010   Prob(JB):                        0.101
Kurtosis:                       4.180   Cond. No.                         18.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

ARDL

In [69]:
from statsmodels.tsa.ardl import ARDL

In [81]:
ardl_data = merged_df[['Canara', 'Nifty']].dropna()

In [82]:
from statsmodels.tsa.ardl import ARDL

model_ardl = ARDL(
    ardl_data['Canara'],
    lags=1,
    exog=ardl_data[['Nifty']],
    order=1
)

result_ardl = model_ardl.fit()

print(result_ardl.summary())

                              ARDL Model Results
==============================================================================
Dep. Variable:                 Canara   No. Observations:                 1655
Model:                     ARDL(1, 1)   Log Likelihood               -2792.530
Method:               Conditional MLE   S.D. of innovations              1.309
Date:                Fri, 11 Sep 2026   AIC                           5595.060
Time:                        10:25:31   BIC                           5622.115
Sample:                             1   HQIC                          5605.090
                                 1655
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.5998      0.219     -2.733      0.006      -1.030      -0.169
Canara.L1      0.9949      0.002    472.655      0.000       0.991       0.999
Nifty.L0       0.0049      0.000     27.344      0.000       0.005       0.005
Nifty.L1      -0.0048      0.000    -26.916      0.000      -0.005      -0.004
==============================================================================

C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

In [83]:
models = {}

for p in range(1, 4):
    for q in range(0, 4):
        
        model = ARDL(
            ardl_data['Canara'],
            lags=p,
            exog=ardl_data[['Nifty']],
            order=q
        )
        
        result = model.fit()
        
        models[f'ARDL({p},{q})'] = result

C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

In [84]:
aic_table = pd.DataFrame({
    name: {
        'AIC': result.aic,
        'BIC': result.bic
    }
    for name, result in models.items()
}).T

print(aic_table.sort_values('AIC'))

                   AIC          BIC
ARDL(3,2)  5590.834234  5634.112170
ARDL(3,1)  5591.558410  5629.426604
ARDL(2,2)  5592.306339  5630.178769
ARDL(3,3)  5592.718498  5641.406176
ARDL(2,1)  5593.071307  5625.533389
ARDL(2,3)  5593.936372  5637.219149
ARDL(1,1)  5595.060142  5622.114902
ARDL(1,2)  5595.953534  5628.419245
ARDL(1,3)  5597.535310  5635.411974
ARDL(3,0)  6188.997856  6221.456308
ARDL(2,0)  6190.511900  6217.563635
ARDL(1,0)  6195.122030  6216.765838

In [85]:
model_ardl2 = ARDL(
    ardl_data['Canara'],
    lags=3,
    exog=ardl_data[['Nifty']],
    order=2
)

result_ardl2 = model_ardl2.fit()

print(result_ardl2.summary())

                              ARDL Model Results
==============================================================================
Dep. Variable:                 Canara   No. Observations:                 1655
Model:                     ARDL(3, 2)   Log Likelihood               -2787.417
Method:               Conditional MLE   S.D. of innovations              1.308
Date:                Fri, 11 Sep 2026   AIC                           5590.834
Time:                        10:27:07   BIC                           5634.112
Sample:                             3   HQIC                          5606.879
                                 1655
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.5983      0.220     -2.715      0.007      -1.031      -0.166
Canara.L1      0.9504      0.025     38.570      0.000       0.902       0.999
Canara.L2      0.0269      0.032      0.850      0.395      -0.035       0.089
Canara.L3      0.0179      0.020      0.876      0.381      -0.022       0.058
Nifty.L0       0.0049      0.000     27.309      0.000       0.005       0.005
Nifty.L1      -0.0045      0.000    -16.140      0.000      -0.005      -0.004
Nifty.L2      -0.0004      0.000     -1.648      0.100      -0.001    6.77e-05
==============================================================================

C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

In [86]:
model_ardl3 = ARDL(
    ardl_data['Canara'],
    lags=1,
    exog=ardl_data[['Nifty']],
    order=1
)

result_ardl3 = model_ardl3.fit()

print(result_ardl3.summary())

                              ARDL Model Results
==============================================================================
Dep. Variable:                 Canara   No. Observations:                 1655
Model:                     ARDL(1, 1)   Log Likelihood               -2792.530
Method:               Conditional MLE   S.D. of innovations              1.309
Date:                Fri, 11 Sep 2026   AIC                           5595.060
Time:                        10:27:58   BIC                           5622.115
Sample:                             1   HQIC                          5605.090
                                 1655
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.5998      0.219     -2.733      0.006      -1.030      -0.169
Canara.L1      0.9949      0.002    472.655      0.000       0.991       0.999
Nifty.L0       0.0049      0.000     27.344      0.000       0.005       0.005
Nifty.L1      -0.0048      0.000    -26.916      0.000      -0.005      -0.004
==============================================================================

C:\Users\admin\anaconda3\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)